# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=folk.sisby
user=sisby-folk
slug=origins-minus
modId=origins_minus
modName=Origins Minus
modDescription=Origins focused on simplicity, not balance.
authors=Sisby folk, Garden System
contributors=DansOtherClone
license=LGPL-3.0-or-later
# Mod Version
baseVersion=2.2.1
# Branch Metadata
branch=1.18
tagBranch=1.18
compatibleVersions=1.18.2
compatibleLoaders=fabric, quilt, forge
